---
name: DrocsidePlugin
version: 1.3.2
author: DOorDIE
description: "その手に希望と夢を。鯖に活力と秩序を。"
website: ~
#依存するプラグイン
depand: []
#---
main: jp.dip.drocside.drocsideplugin.DrocsidePlugin
commands:
    kill:
        description: 皆殺しのお手伝いしちゃう！！
        usage: /<command>
    serverinfo:
        description: ~
        usage: ~
    testteiki:
        description: ~
        usage: ~
    tp:
        description: ~
        usage: ~
    tpa:
        description: ~
        usage: ~
    tpahere:
        description: ~
        usage: ~
    tpt:
        description: ~
        usage: ~
    sabamiso:
        description: ~
        usage: ~
    toro:
        description: ~
        usage: ~
    jail:
        description: ~
        usage: ~
        permission: drocside.penalty.jail
    unjail:
        description: ~
        usage: ~
        permission: drocside.penalty.jail
    mute:
        description: ~
        usage: ~
        permission: drocside.penalty.mute
    unmute:
        description: ~
        usage: ~
        permission: drocside.penalty.mute
    ban:
        description: ~
        usage: ~
        permission: drocside.penalty.ban
    unban:
        description: ~
        usage: ~
        permission: drocside.penalty.ban
    kick:
        description: ~
        usage: ~
        permission: drocside.penalty.kick
permissions:
    drocside.tp.ignore:
        description: /tptの無視
        default: op
    drocside.penalty.*:
        description: BAN・UNBAN・ミュート・KICK・JAIL・UNJAIL
        default: op
    drocside.penalty.mute:
        description: ミュート
        default: op
    drocside.penalty.ban:
        description: BAN・UNBAN
        default: op
    drocside.penalty.kick:
        description: KICK
        default: op
    drocside.penalty.jail:
        description: JAIL
        default: op


